# Generated by Django 5.2.17 on 2026-08-08 15:27
#
# Every model below has managed = False (see farm/models.py), so Django's
# schema editor SKIPS the actual CREATE TABLE for each of these operations
# at migrate time — they exist purely so Django's migration state/history
# knows about these models (needed for admin, ContentTypes, etc). The real
# tables, checks, and triggers already exist in Supabase from Phase 4/7.
# `manage.py migrate` still needs to run once, but only to create Django's
# OWN internal tables (auth_user, django_session, django_admin_log, ...).

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('crop_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('crop_type', models.CharField(max_length=100)),
                ('planting_date', models.DateField()),
                ('expected_harvest_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('plot_number', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'crop',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CropFertilizer',
            fields=[
                ('pk', models.CompositePrimaryKey('crop_id', 'fertilizer_id', 'usage_date', blank=True, editable=False, primary_key=True, serialize=False)),
                ('usage_date', models.DateField()),
                ('quantity_used', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'crop_fertilizer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CropWorker',
            fields=[
                ('pk', models.CompositePrimaryKey('crop_id', 'worker_id', 'assigned_date', blank=True, editable=False, primary_key=True, serialize=False)),
                ('assigned_date', models.DateField()),
                ('task_role', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'crop_worker',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('contact_details', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('equipment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('equipment_name', models.CharField(max_length=255)),
                ('equipment_type', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='Available', max_length=50)),
            ],
            options={
                'db_table': 'equipment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('farm_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('farm_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('total_size', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'farm',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('fertilizer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fertilizer_type', models.CharField(max_length=100)),
                ('stock_level', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'fertilizer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('harvest_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('harvest_date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'harvest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HarvestSale',
            fields=[
                ('pk', models.CompositePrimaryKey('harvest_id', 'sale_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('quantity_sold', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'harvest_sale',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('sale_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sale_date', models.DateField()),
                ('invoice_number', models.CharField(max_length=100, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'sale',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('worker_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('contact_details', models.CharField(blank=True, max_length=255, null=True)),
                ('job_role', models.CharField(blank=True, max_length=100, null=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'worker',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkerEquipment',
            fields=[
                ('pk', models.CompositePrimaryKey('worker_id', 'equipment_id', 'assigned_date', blank=True, editable=False, primary_key=True, serialize=False)),
                ('assigned_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'worker_equipment',
                'managed': False,
            },
        ),
    ]
