# Generated by Django 5.2.17 on 2026-08-09 01:28
#
# Unlike 0001_initial (all managed=False, no real DDL runs), this
# migration DOES create a real table — `farm_workerprofile` — since
# WorkerProfile is Django-owned. This is the one migration in this app
# that `manage.py migrate` actually acts on against Supabase.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker_profile', to=settings.AUTH_USER_MODEL)),
                ('worker', models.OneToOneField(blank=True, help_text='Required for Farm Manager / Field Worker accounts. Leave blank for Sales Clerk.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='farm.worker')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
